### PR TITLE
added Go Module support

### LINKED ISSUE #215: Question: Module Support with Faktory
OS: macOS Mojave 10.14.2
Go Version: `1.12.4`

With the Go version I am using, I have module support enabled.  I want to follow the [Go example](https://github.com/contribsys/faktory_worker_go#usage), so I simply copy and paste that code into `main.go`.

#### main.go
```
package main

import (
	"fmt"
	worker "github.com/contribsys/faktory_worker_go"
)

func someFunc(ctx worker.Context, args ...interface{}) error {
	fmt.Println("Working on job", ctx.Jid())
	return nil
}

func main() {
	mgr := worker.NewManager()

	// register job types and the function to execute them
	mgr.Register("SomeJob", someFunc)
	//mgr.Register("AnotherJob", anotherFunc)

	// use up to N goroutines to execute jobs
	mgr.Concurrency = 20

	// pull jobs from these queues, in this order of precedence
	mgr.ProcessStrictPriorityQueues("critical", "default", "bulk")

	// alternatively you can use weights to avoid starvation
	//mgr.ProcessWeightedPriorityQueues(map[string]int{"critical":3, "default":2, "bulk":1})

	// Start processing jobs, this method does not return
	mgr.Run()
}
```

When I run `go build`, I receive the following:
```
go: finding github.com/contribsys/faktory/client latest
build faktory-test: cannot load github.com/contribsys/faktory/client: cannot find module providing package github.com/contribsys/faktory/client
```

If I turn module support off, the program builds (though I had to add the `"fmt"` import)

Am I doing something incorrectly to build this with module support?  Or is that something that is not supported?

### PR DESCRIPTION
**Pull request by ClaytonNorthey92**
fixes #215 

added both go.mod and go.sum files to treat this repository as a module

anyone looking to install this as a dependency via Go Modules can do so now

**Please Note** The wiki will have to be updated after this is merged, I can do it, but this will need to be merged first.  We need to add the following in the installation section:

If you are using Go Modules, you need to ensure that you `go get` the faktory dependency, this will inform Go what module contains the `client` package.  You also need to make sure you get a version that includes the Go Module files.

```
go get -u github.com/contribsys/faktory@<branch, tag, or commit that contains the Go module files>
```

### CODE REVIEW

**Comment by mperham** [comment]
I’m not clear how this affects my daily dev process and how I need to maintain these files.

**Comment by ClaytonNorthey92** [comment]
sorry for the delayed response

if you are not using Go Modules, I don't believe this would effect your daily workflow.

if you are using Go Modules and working on this repository, from the [Go Wiki](https://github.com/golang/go/wiki/Modules):

> Your typical day-to-day workflow can be:
> * Add import statements to your .go code as needed.
> * Standard commands like go build or go test will automatically add new dependencies as needed to satisfy imports (updating go.mod and downloading the new dependencies).
> * When needed, more specific versions of dependencies can be chosen with commands such as go get foo@v1.2.3, go get foo@master, go get foo@e3702bed2, or by editing go.mod directly.

so if you ever needed to use a later/older (different) version of a dependency, you would need to update the files similar to as specified above


if you were developing on a project that depended on this repository and using Go Modules (for example, the [Go Faktory Worker](https://github.com/contribsys/faktory_worker_go/blob/master/runner.go#L14)) and imported a package, you would need to make sure you included that module in that project's `go.mod` via `go get` and specifying a version that includes module support.  You need to specify the version (or branch or tag or hash) if the latest non-alpha version does not include it, I believe by default it will attempt to use the latest non-alpha version


does that help?

**Comment by mperham** [comment]
Cool, sounds reasonable and not any harder than `dep ensure`.  I have a complexity in that I need to port the commercial Faktory Pro repo to use modules at the same time so give me some time to play with this, grok it and roll it out.  I'm not sure I can backport this to v1.0 but perhaps this can be part of a v1.x release that targets Go 1.13 in August.

**Comment by ClaytonNorthey92** [comment]
thanks @mperham let me know if you need me to do anything further

**Comment by ClaytonNorthey92** [comment]
@mperham I got rid of installing dep in the Makefile (with `make prepare`).  Go Modules should replace it for package management.   I ran `make prepare` and `make test` as well as building the Docker image with `make dimg` then running it with `docker run (tag)` and all are working okay.

**Comment by xescugc** [comment]
I would say that maybe the `Gopkg.*` can be removed too because Go Modules already has it's own.

**Comment by ClaytonNorthey92** [comment]
@xescugc ah yes good point, I should remove the dep files, I can do that

**Comment by mperham** [comment]
I'm waiting for the 1.13 release to merge this. I'll upgrade the Go runtime version at the same time.

**Comment by zhaolion** [comment]
go 1.13 is already released

**Comment by mperham** [comment]
@zhaolion Don't be rude. I don't need reminders from anonymous strangers to do work.

**Comment by mperham** [comment]
Build is failing, I have no experience with modules so I can't figure it out.  If anyone has a moment, any ideas?  The ego binary is part of `github.com/benbjohnson/ego`.

https://circleci.com/gh/contribsys/faktory/116

**Comment by tylerb** [comment]
You may just need to add `go install github.com/benbjohnson/ego` to your circleci config.

**Pull request merged**
