### PR TITLE
Fix race conditions

### PR DESCRIPTION
**Pull request by andrewstucki**
See https://github.com/contribsys/faktory/issues/27

### CODE REVIEW

**Comment by mperham** [comment]
I'm a little worried that this increases the code complexity for little benefit.  It doesn't matter if the stats load 123456 or 123457, that race condition is superfluous, right?  I'll need to look more into the maps issue.

**Comment by andrewstucki** [comment]
I think you're right in saying that the Loads aren't that big of a deal -- the main thing that they're going to cause are inconsistent reads, the Stores (instead of setting thee variable directly) are probably a bigger deal.

That said, if you do want to push back on the Loads, I'd be more concerned that running without the race detector enabled is going to result in more problematic concurrency issues down the line.

**Comment by mperham** [comment]
I see your point: either ignore the race detector or use it and (appease the machine or deal with a lot of noise).

**Comment by mperham** [comment]
There's a conflict that needs to be fixed.

Can we make the race detector optional?  Test suite currently takes about 5 seconds, good for TDD, but the race detector makes it more like 30 seconds right now.

**Comment by andrewstucki** [comment]
Sure, I can make it optional and fix the conflict.

**Comment by andrewstucki** [comment]
@mperham - Hid the race detector behind the `DETECT_RACES` environment variable, set it to anything and it adds `-race` -- also made it so you can override the test flags that get passed in wholesale.

**Pull request merged**
