### PR TITLE
WIP: CSRF protection

### LINKED ISSUE #63: Add CSRF protection
The Web UI currently is missing CSRF protection because we don't have any notion of session to store the current token value.  The hooks are all there in the forms to inject an authenticity_token, we just need to implement it.

### PR DESCRIPTION
**Pull request by vosmith**
Added the [justinas/nosurf](https://github.com/justinas/nosurf) library for CSRF protection and modified the `csrfTag` helper function to support it. closes #63

### CODE REVIEW

**Comment by mperham** [comment]
Is it possible to add a test showing the CSRF protection working?

**Comment by vosmith** [comment]
Yes sir, I'll be working on the test cases next.  Looks like some of the other `webui` tests are broken as well.

**Comment by vosmith** [comment]
Sorry for this being long overdue.  I ran into issues with the test cases.  Since nosurf adds its own context to the requests, the DefaultContext was causing panics when the test cases sent requests directly to the Handlers.  I've modified the DefaultContext to accept a boolean flag indicating whether or not CSRF should be verified.

**Comment by mperham** [comment]
why does it need to be on the context?  Why not a global since it never changes?

**Comment by vosmith** [comment]
Are you still considering it as is, or should I go ahead and make the change?

**Comment by mperham** [comment]
Put in a global and have the context use the global for now.

**Comment by vosmith** [comment]
I've created a global variable which is referenced by the DefaultContext and updated the test cases.  Let me know what you think.

**Comment by mperham** [comment]
Thank you!  I will get this into the forthcoming 0.6.2 release this week.

**Pull request merged**
