### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by andrewstucki**
So, there are some dragons in building this on Travis:

1) As mentioned here: https://github.com/contribsys/faktory/issues/23, rocksdb appears to be trying to build in compression support if any compression headers are found (so we remove zlib and libbz2 dev packages)
2) Travis moves the checkout for (forked) branches based off the repo it pulls from which breaks dependencies unless you move it to `$GOPATH/src/github.com/contribsys/faktory`

### CODE REVIEW

**Comment by mperham** [comment]
I'm worried because RocksDB takes 8-10m to compile so each commit would incur that rebuild, right?  Perhaps we should build a static lib on Travis once and cache that result somewhere.  Maybe Travis has some sort of caching we can use?  That would take the CI build from 10m to about 10s.

**Comment by andrewstucki** [comment]
Sure, I can take another crack at caching, I was having issues with doing so earlier when I had it checking out to a subdirectory of the project instead of `$HOME`

**Comment by andrewstucki** [comment]
@mperham there we go on the caching, build takes a little less than a minute now

**Comment by mperham** [comment]
What happens when we want to upgrade a vendor dep or the rocksdb version?  How do we bust the cache?

**Comment by andrewstucki** [comment]
The vendor dep stuff should still work because of the `make prepare` step and how `dep ensure` works. The rocksdb updates you would have to manually bust the cache in travis through the UI/cli at the moment. I can try and write a conditional check for version type on the build guard if you'd prefer.

**Comment by mperham** [comment]
Nah, think simpler: throw the version in the directory name.  :-)

**Comment by andrewstucki** [comment]
Ok, think I have a tenable solution. Just waiting for the build to pass in travis.

**Comment by andrewstucki** [comment]
Cool, build looks great now

**Comment by mperham** [comment]
One thing I noticed: you remove libz and libbz2 but that will build rocks without any compression support at all.  We want data compression and we want it statically linked into the binary.  To do that, you need to tell rocks to build libsnappy.a first.

https://github.com/contribsys/faktory/blob/master/build/centos/setup.sh#L22

**Comment by andrewstucki** [comment]
As far as I can tell, the builds vagrant boxes don't use compression. Copied from #23:

> https://github.com/facebook/rocksdb/blob/master/build_tools/build_detect_platform seems to enable compression if it finds zlib or libbz2 headers, which are both on travis build machines by default.

It looks like it's the same for snappy and lz4 support. If you build out `librocksdb.a` in either Vagrant machine and do `nm librocksdb.a  | grep snappy_compress` you don't get any symbols. Same is true if you build out the binary and then do `nm faktory | grep snappy_compress`. Running `nm` on librocksdb.a needs to return undefined symbol references to the different compression libraries if you want it to have compression support.

I believe this is happening because of the `build_detect_platform` script referenced above not finding any headers for snappy since they aren't in the default location on the system.

That being said, if compression is wanted and we want to build rocksdb statically we'll need to add linker flags for the compression libraries that we want to build against in `github.com/contribsys/gorocksdb`.

**Comment by mperham** [comment]
I was under the impression that if you build libsnappy.a, then librocksdb.a will contain it.  If not true, we need to fix that, yeah.  The lines you are looking for are right here:

https://github.com/contribsys/gorocksdb/blob/master/dynflag.go#L4

**Comment by mperham** [comment]
Those dynflag options control libraries that are dynamically linked to the Go binary.  We want static linking, so maybe that means we need to massage the rocks build instead.

**Comment by andrewstucki** [comment]
## gorocksdb linker flags

Well, I'm not super familiar with linkers, but here's from the binutils docs:

> -l namespec
> --library=namespec
>
> Add the archive or object file specified by namespec to the list of files to link. This option may be used any number of times. If namespec is of the form :filename, ld will search the library path for a file called filename, otherwise it will search the library path for a file called libnamespec.a.

So, the thing that's actually linking in `librocksdb.a` is the `-lrocksdb` flag in `dynlib.go` coupled with the path inclusion from adding in `-L$ROCKSDB_HOME` to the linker flags.

## Static v. Dynamic linking

Normally, if rocksdb and it's dependencies were compiled dynamically then the rocksdb dynamic library would have all of the linking info baked into it. However, since it's compiled statically, the undefined symbols that would result from adding compression support at compile time to the static library need to be resolved by additionally linking dependencies at the time that `gorocksdb` is built.

Interestingly enough on Mac, running `otool -L /usr/local/Cellar/rocksdb/5.8/lib/librocksdb.dylib` on the library provided from Homebrew shows a dynamic libsnappy--so you shouldn't need the `-lsnappy` linker flag on OSX if we want to use Homebrew installed rocksdb.

## So...

There are two options here for building this in Travis with compression:

1) It looks like adding `-lsnappy` to either global CGO build flags or the linux specific ones in `gorocksdb` might do the trick (assuming that `libsnappy.a` exists in the same directory as `librocksdb.a`). Once again though, from the looks of it, that means that lz4, bz2, and zip compression aren't going to be supported without adding in their corresponding linker flags and building the corresponding static libraries or linking to available system libraries.
2) We can try manually overriding the build flags using the same process as the `gorocksdb` README where we specify the library linker flags directly rather than relying on the flags inside of the go source.

Do you want to just hold off on this while fixing `gorocksdb`, should we just try overwriting the linker flags directly to add in snappy support, or is it ok just to build in CI with compression turned off?

**Comment by mperham** [comment]
Good research.  rocks allows the developer to configure the compression method.  we don't want that flexibility, snappy is the default so I want to statically link in snappy and avoid any use/need for gz, bz2, lz4, etc to minimize runtime dependencies.  gorocksdb doesn't use snappy directly, it's an internal rocks thing.

**Comment by mperham** [comment]
perfect should not be the enemy of good.  this is an improvement so I'll merge as is.

**Comment by mperham** [comment]
I just realized that the build `strip`s librocksdb.a so your symbol search may fail for that reason.

**Comment by andrewstucki** [comment]
@mperham I don't believe that the call to `strip` would remove undefined symbols--just debug symbols (it's using `-g`). Either way, confirmed with the non-stripped library that the symbols still aren't there.

I'm building out another static rocksdb right now with snappy support and I'll post the comparison results for reference.

**Comment by andrewstucki** [comment]
Here you go:

```
[vagrant@localhost rocksdb]$ nm -u librocksdb.a | grep snappy
                 U _ZN6snappy11RawCompressEPKcmPcPm
                 U _ZN6snappy19MaxCompressedLengthEm
                 U _ZN6snappy13RawUncompressEPKcmPc
                 U _ZN6snappy21GetUncompressedLengthEPKcmPm
```

And the output without the with the current build process (without stripping):

```
[vagrant@localhost rocksdb]$  nm -u librocksdb.a | grep snappy
```

**Comment by mperham** [comment]
🤘 Definitely want to fix that.  Compression support would be tight _cough_.  It's huge for jobs that take large arguments.

**Pull request merged**
