### PR TITLE
Protocol version 2 changes

### PR DESCRIPTION
**Pull request by mperham**
* A nil response, e.g. FETCH response, is now correctly sent as `$-1\r\n`, per RESP docs.
* Add `HI "i"` random hash iterations count, for defense against rainbow tables
* Change `HI "v"` value in JSON from String to int, this was a “whoops” by me
* Clients should advise the server of their requested protocol version with `HELLO "v"`.  This way the server can elect to kill the connection immediately to disallow old clients.
* The`"signal"` JSON key within the BEAT response has been renamed to "state" to better reflect intent.

TLS socket support has been removed from the Faktory server.  The Faktory client APIs can still be configured to connect to a TLS socket.

### CODE REVIEW

**Comment by mperham** [comment]
It is likely that any official authentication standards (e.g. SCRAM, SASL) support would be pushed into a commercial version.

**Comment by jonhoo** [comment]
Just to clarify, the response to `BEAT` hasn't actually changed -- it is still just a REDIS RESP string response? We should be careful about enumerating exactly what has changed in terms of the on-the-wire responses when the version changes.

**Comment by mperham** [comment]
Correct, the -1 NIL change is the only wire-level change.  Everything else is a change in JSON blob contents.

**Comment by jonhoo** [comment]
> Correct, the -1 NIL change is the only wire-level change.

This should probably be in the list in the first post.

> Everything else is a change in JSON blob contents.

Specifically just the ones listed above, or are there more?

**Comment by mperham** [comment]
Updated with all the significant changes I know about.

**Comment by jonhoo** [comment]
It is worth pointing out that `i` is only included when `s` is included.

**Pull request merged**
