### PR TITLE
Add client/pool to provide a thread-safe pool of clients

### PR DESCRIPTION
**Pull request by tylerb**
`client/pool/pool.go` provides a pool of clients and manages their lifecycle appropriately.

This is the initial implementation and may not be exactly what you want, @mperham, but I'd love to go back and forth to arrive at a final implementation.

### CODE REVIEW

**Comment by tylerb** [comment]
Also, if you check the test, you'll see I have comments in there about a case that I need to test but can't figure out how to do it. Your assistance would be appreciated here.

**Comment by mperham** [comment]
Seems pretty good already.  What about putting the Pool directly in the faktory/client package, rather than a subpackage?

**Comment by tylerb** [comment]
I'm fine putting it in the same package, certainly. I like the separation, myself, but I also have a tendency to over-separate code. I'll give it a go and update the PR.

**Comment by tylerb** [comment]
Ok, I've rewritten it so that it is much cleaner, and doesn't need so many overrides.

I *did* have to add a field and some custom behavior to the existing `Client` object, which I was trying to avoid in the previous implementation.

Hopefully this isn't an issue. Let me know what you think. Thanks!

**Comment by mperham** [comment]
I’m not clear where poolConn is used in the client instance, aside from markUnusable. Can you write to one socket and read the response from another?

**Comment by tylerb** [comment]
It's only used for `markUnusable`. We check for a transport-level error and then mark it unusable. I pushed that down to the `Client` level so that we could be that granular with when we marked it unusuable.

I'm not sure what you mean by write to one socket and read the response from another.

**Comment by mperham** [comment]
I'm not sure I like this implementation -- it was really surprising to me to learn that if I get a client from a pool, the Close method is different from the normal client Close method, with completely different semantics. I'm not a fan of pools that can leak their elements if the user does not use them appropriately, like forgetting to call Close().

What do you think about a pool implementation which provides a client scoped to a closure, something like:

```go
pool.with(func(cl faktory.PoolClient) error {
  return cl.Ack(jid)
})
```

**Comment by mperham** [comment]
I can see your logic there.  Do you think the methods named `Get` and `Close` are confusing?  I think it would be clearer with names like "Checkout" and "Checkin", so the developer knows that they are performing pool operations.

What do you think about providing all three methods: scoped `With`, "Checkin" and "Checkout"?

**Comment by tylerb** [comment]
I don't personally think they are confusing. I modeled them after https://github.com/gomodule/redigo, an extremely popular redis client for Go. The same argument applies here: it's an idiom that is widely used and accepted by the Go community.

https://github.com/gomodule/redigo/blob/master/redis/pool.go#L187
https://github.com/gomodule/redigo/blob/master/redis/pool.go#L260

Additionally, the standard library `sync/pool` uses `Get` for acquiring an object. 

https://golang.org/pkg/sync/#Pool

I would prefer to stick with `Get` and `Close`, but it's your project. If you'd prefer some other names, we can certainly do that. I'm not a huge fan of `Checkin` or `Checkout`, but something like `Reserve/Acquire` and `Release` would be fine by me.

As for the `With` method, I don't have any strong arguments against it, other than adding complexity to the API. Given the existence of `defer`, I feel the scoped closure approach is not quite as necessary as it might be in other languages.

```go
c := pool.Get()
defer c.Close()
```

Is far easier to type and remember than:


```go
pool.with(func(cl faktory.PoolClient) error {
  return cl.Ack(jid)
})
```

The last option I'll throw into the pot is `Put` instead of `Close`. This is how `sync/pool` does it.

```go
c := pool.Get()
defer pool.Put(c)
```

Doing it that way will remove the overload of semantics for `Close` on a pool connection vs `Close` on a normal connection, and make it clear that we are grabbing something from the pool then giving it back.

**Comment by mperham** [comment]
Great comment, I'm all in favor of sticking with Go stdlib idioms and the `sync` API.  I like `Get`/`Put`, it avoids overloading Close.

**Comment by tylerb** [comment]
Great! I'll see what I can do about getting that done sometime soon. In a bit of crunch time right now, so I may not get to it for a week, perhaps even two.

**Comment by tylerb** [comment]
I've been taking a look at the code and hit a few problems.

Adding the `pool.Put(client)` method works just fine. However, the problem with that is we will *still* have a `Close()` method on the `PoolClient` that comes back, since it embeds the `Client`. Having both `pool.Put()` and `client.Close()` is confusing.

So our options there would be:

1. `poolClient.Close()` is a no-op
	1. This opens up the possibility of misuse, where the programmer thinks they are closing it but they really aren't. Given that this is a common idiom, I can see this happening frequently.
2. `PoolClient` has an instance of `Client` instead of embedding it, and we leave out the `Close` method entirely.
	1. This means we would have to duplicate each method and call the embedded client's corresponding method.
3. `PoolClient` becomes an interface, leaving out the `Close` method, and `Get` returns that interface.
	1. We would have to duplicate the method signature for any method we wanted to expose from the base client.
	2. We have to make a type assertion to the internal `poolClient` type in order to access the `poolConn` to close it and return it to the pool. If someone, for some reason, creates a new implementation of that interface and passes that to `Put()`, we will be unable to make the assertion in order to close the `poolConn`.
	3. It violates the "return a concrete, accept an interface" go "rule".

None of these options are particularly attractive.

If we stick with `pool.Get` and `poolClient.Close`, all of the issues described above simply go away, and we get all the methods on the underlying `Client` for free. It would require no extra work on our part when adding new functionality and it also maintains a clean interface.

Given that `Get/Close` is a common go idiom, and the extra issues described above, I think we may want to consider sticking with `Get/Close`, even with the overload of the `Close` functionality. It feels like the lesser of the evils.

**Comment by mperham** [comment]
All good points. What about not using Close at all, i.e. `pool.Put(poolConn)` instead of `poolConn.Close`?

**Comment by tylerb** [comment]
Using `pool.Put` is what causes all the issues I outlined above. It's certainly doable, but with drawbacks for the various options.

**Comment by mperham** [comment]
Oh sorry, I missed that in reading the full comment. Can we ditch the PoolClient special type and have the pool Get/Put() faktory/client.Client directly?

**Comment by tylerb** [comment]
We could do that, but we would still have the `Close` method on the client itself. It would be confusing, and if someone called `Close` on the client, then put it back in the pool, it would cause all kinds of problems.

From what I've seen in other libraries, the design is such that you can only retrieve an instance of the client through the Pool. There is no concept of an individual client. All the issues we are facing here are the result of the `Client` object existing as an exposed type.

Were we to re-work this so that the pool is the only way to retrieve a "client", all of these problems go away. Obviously that would be a breaking change.

**Comment by mperham** [comment]
My experience is clouded by the `connection_pool` gem that I maintain for Ruby.

`faktory.Client` wraps a single socket to Faktory and it's not safe to share.  Call Close and the socket is closed, easy to understand. A `faktory.Pool` type that can Get/Put() `faktory.Client` makes perfect sense to me, I don't see the need to hide it. I get that other libraries like go-redis have a different API. Users can choose to use a Client directly or use a Pool of Clients. Is there a serious drawback that I've forgotten?

**Comment by tylerb** [comment]
The only serious drawback, to me, is having the `Close` method on the client that comes back from the pool. There are three reasons:

1. I feel that the pool should be in charge of the lifecycle of a connection. This should be transparent to the user.
2. It is confusing. Which do I use? `Put` or `Close`?
3. Because `Get` followed by `Close` is a common idiom in other packages, it is quite likely someone will call `Close` without understanding that they should use `Put`. I normally try not to worry about footguns too much, but I can see how this one would be more of a concern.

If we want to just do `Get/Put` and not worry about there being a `Close` method on the object, we can certainly do that.

**Comment by mperham** [comment]
Let's do that. A little GoDoc should minimize confusion.

**Comment by mperham** [comment]
Much simpler, I like it.  Thanks for your patience, I'll merge this; I might add a helper `with` function to supply that closure-based API as already used in fwg.

**Pull request merged**
