### PR TITLE
expose tls.Config{} through the Server struct

### PR DESCRIPTION
**Pull request by cdrx**
I needed to move the environment variable passing stuff to a method on the `Server` struct, because the existing package level `Open` method doesn't provide any mechanism to adjust the `Server` properties before `Dial`. 

It would have been cleaner to move the env var parsing into `DefaultServer()` but that wouldn't be possible without adding `err` to the return type which would change the public API. 

There is a corresponding PR for `faktory_worker_go` that adds a `Server` struct to the `Manager` struct so the user of the library can adjust the tls.Config settings

### CODE REVIEW

**Comment by mperham** [comment]
I was waiting to review this because your description says you have a PR for faktory_worker_go but I haven't seen anything come thru.  Is this pending?

**Comment by cdrx** [comment]
Ah, sorry. I was waiting for feedback on this before pushing it, I should have been explicit.

The changes to `faktory_worker_go` are tiny -- just adding `*faktory.Server` to the `Manager` struct and using `server.Open()` rather than `faktory.Open()` in the `NewChannelPool`. 

That allows the end user of the worker lib to adjust server.TLS settings before connecting to the server.

**Comment by mperham** [comment]
lgtm

**Comment by cdrx** [comment]
Thanks! I’ll open a PR for the worker tomorrow

**Pull request merged**
