### PR TITLE
Adding locale preferences to the debug page

### PR DESCRIPTION
**Pull request by vosmith**
This commit allows users to select their preferred locale from the debug page.  This adds a new row to the debugging table with a select box with all available locales in the system.  Changing the selection automatically reloads the browser into the selected locale.  The user's preference is persisted by a simple cookie, which overrides the browser `Accept-Language` header.

### CODE REVIEW

**Comment by mperham** [comment]
You've got a bunch of whitespace changes which are adding noise to the PR.  Any way you can revert that?

**Comment by andrewstucki** [comment]
@mperham cool Github tip I learned awhile ago, add [?w=1](https://github.com/contribsys/faktory/pull/71/files?w=1) to the url to view a PR sans whitespace changes.

**Comment by vosmith** [comment]
I'll see if I can fix this, I think it happened after running `make fmt`?

**Comment by mperham** [comment]
Looks like you undented a section of the HTML for some reason, perhaps accidentally.

**Pull request merged**
