### PR TITLE
Support a global configuration file, #46

### PR DESCRIPTION
**Pull request by mperham**
Right now we don’t have anywhere to add misc config knobs.  Faktory has a minimum of tunable features but we’ll inevitably get some features which don’t have a default value that works for all use cases.  This gives us flexibility for the future.

Viper pulls in too many transitive dependencies and is overly flexible.  We insist on a single, simple format (TOML) in one of two well-known locations:

/etc/faktory/config.toml
~/.faktory/config.toml

TODO Support HUP signal to reload global config without restarting the daemon.

### CODE REVIEW

**Comment by agnivade** [comment]
> Viper pulls in too many transitive dependencies and is overly flexible.

Ah too bad. Viper supports auto-config reload on file save. So the case for supporting config reload would have been automatically taken care of.

**Comment by mperham** [comment]
I'm digging HJSON as an alternative format.  I prefer the ability to nest, map-style, to TOML's odd INI style for nesting data.

https://github.com/hjson/hjson-go

**Comment by jweslley** [comment]
@mperham why not YAML!?

**Comment by mperham** [comment]
YAML is whitespace-sensitive, making for obscure error messages.

**Comment by mperham** [comment]
It also has a history of security problems due to it's overly complex design.

**Comment by spinx** [comment]
https://github.com/hashicorp/hcl is json compatible

and you can add interpolations on top if the need arises in the future
https://github.com/hashicorp/terraform/blob/b002b4303b83f856b851622df9192972ae5191e5/config/interpolate_funcs.go

**Comment by mperham** [comment]
HCL looks interesting but a much bigger dependency than BS/toml, which is smaller and more stable.  I think the syntax is good mix of flexible and simple.  We'll see how it goes.

**Pull request merged**
